codecov:
  max_report_age: off
  notify:
    wait_for_ci: false
  require_ci_to_pass: false
comment:
  require_base: false
  require_head: false
coverage:
  status:
    project:
      default:
        threshold: 0.07
